#!/bin/sh

grep -oE 'refs/tags/[^ ]+' | cut -c11- | while read -r tag; do
  if ! printf %s\\n "$tag" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+'; then
    echo 'Tags must start with a v, followed by a pure semver, e.g. v1.4.5'
    exit 1
  fi
done
